"""User Model Update

Revision ID: e775154e5433
Revises: a84cea2f7164
Create Date: 2024-07-13 12:46:50.095365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e775154e5433'
down_revision: Union[str, None] = 'a84cea2f7164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_false', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
